---
version: "2.1"
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      # - MENU_VERSION=1.9.9 #optional
      # - PORT_RANGE=30000:30010 #optional
      # - SUBFOLDER=/ #optional
    volumes:
      - ./config:/config:ro
      - ./assets:/assets #optional
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80 #optional
  dhcp:
    image: networkboot/dhcpd:latest
    ports:
      # Public dhcpd Port:
      - "67:67/udp"
    volumes:
       - ./dhcp:/data
    network_mode: "host"
    environment:
       - TZ=Asia/Kolkata